name: 'Lint Pull Requests'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Validate a title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            ABC
          scopes: |
            \d+
          requireScope: true
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          headerPattern: '^([A-Z]+)-(\d+)(.*)$'
          headerPatternCorrespondence: type, scope, subject
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
